#ifndef ENUMS_H
#define ENUMS_H

enum RobotMovementState {
  STOPPED,
  FORWARD,
  BACKWARD,
  LEFT,
  RIGHT,
  TURN_SPOT_LEFT,
  TURN_SPOT_RIGHT,
  CW_LEFT,
  CW_RIGHT
};

enum RobotControlState {
  MANUAL,
  LINE_FOLLOW_BANGBANG,
  SOLVE_MAZE_1,
  SOLVE_MAZE_2,
  SOLVE_MAZE_3,
  LOST_ROBOT,
  EMERGENCY_STOP,
  U_TURN,
  PARKING_IN_BOX
};

enum MazeState {
  FOLLOW_LINE,
  TURNING_LEFT, 
  BLIND_TURN,   
  TURNING_RIGHT,
  OBJECT_DETECTED,
  TURNING_180_DEGREES,
  AFTER_180_RIGHT_SENSOR_SEARCH,
  JUNCTION_FOUND,
  SQUARE_UP_JUNCTION,
  DRIVE_THROUGH_INTERSECTION, 
  
  SCAN_LEFT_FOR_LINE,         
  ALIGN_EXTRA_LEFT,           
  
  SCAN_RIGHT_FOR_LINE,
  ALIGN_EXTRA_RIGHT,

  RECOVER_RIGHT_FIND_BLACK,   
  RECOVER_RIGHT_FIND_WHITE,
  RECOVER_LEFT_FIND_BLACK,    
  RECOVER_LEFT_FIND_WHITE, 

  RECOVER_LEFT_IN_ESCAPE,   
  
  LOST_ROBOT1
};

enum LostRobotState {
  SEARCHING_FOR_THE_LINE,
  FOUND_THE_LINE,
};

enum EmergencyStopState {
  BANG_LINE_FOLLOWING,
  EMERGENCY_STOPPED
};

enum ParkingBoxState {
    APPROACHING_PARKING_BOX,
    PARKING_TURNING_LEFT,
    PARKING_TURNING_RIGHT,
    PARKING_BLIND_TURN,
    SELF_ALIGN_90_DEGREES,
    PARKING_SEARCH_START_LINE,
    PARKING_DRIVE_INTO_BOX,
    PARKING_FALLBACK_SEARCH_FOR_END,
    END_OF_PARKING_BOX
};

enum elostLineState {
  SCANNING_LEFT_U,
  SCANNING_RIGHT_U,
  RETURNING,
  REACHED_END
};

#endif